name: "Check Functional Changes"
description: "Checks for functional changes in the codebase"
inputs:
  repo-token:
    description: "Token to access the repository"
    required: true
outputs:
  no_functional_changes:
    description: "A boolean signaling that there are no functional changes in the changeset"

runs:
  using: "composite"
  outputs:
    no_functional_changes: ${{ steps.set_no_functional_changes.outputs.no_functional_changes }}
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make release type available to subsequent jobs
      run: |
        if grep -q "## Unreleased \[no-release\]" CHANGELOG.md; then
          echo "NO_FUNCTIONAL_CHANGES=true" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Print result
      id: set_no_functional_changes
      run: |
        echo "no_functional_changes='${{ env.NO_FUNCTIONAL_CHANGES }}'"
        echo "no_functional_changes=${{ env.NO_FUNCTIONAL_CHANGES }}" >> $GITHUB_OUTPUT
      shell: bash
