name: "Validate Changelog"
description: "Validate the `Unreleased` changelog section, extract the release type, and optionally validate funders and no-release-signature"
inputs:
  path:
    description: "Path to the changelog file. Defaults to './CHANGELOG.md'"
    required: false
  funders:
    description: "A boolean or Regex string to identify funders in the Unreleased section. Set to `true` for default validation, `false` to disable, or provide a custom JavaScript Regex. Defaults to false"
    required: false
  no-release-signature:
    description: "A boolean or Regex string to identify the no-release signature in the Unreleased section. Set to `true` for default validation, `false` to disable, or provide a custom JavaScript Regex. Defaults to true"
    required: false
outputs:
  release-type:
    description: "The release type extracted from the changelog"
runs:
  using: "node20"
  main: "index.js"
