name: Test local actions

on:
  pull_request:

jobs:
  test-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Test default value for funders validation
        id: validate
        uses: ./validate
        with:
          path: ./src/fixtures/changelog-without-funder.md
      
      - name: Test enabling funders validation
        uses: ./validate
        with:
          path: ./src/fixtures/changelog.md
          funders: true

      - name: Test custom value for funders validation
        uses: ./validate
        with:
          path: ./src/fixtures/changelog-with-custom-funder.md
          funders: '/^> This release was sponsored by (.+)\.$/m'

      - name: Test default value for no-release signature validation
        uses: ./validate
        with:
          path: ./src/fixtures/changelog.md
      
      - name: Test disabling no-release signature validation
        uses: ./validate
        with:
          path: ./src/fixtures/changelog.md
          no-release-signature: FALSE

      - name: Test custom value for no-release signature validation
        uses: ./validate
        with:
          path: ./src/fixtures/changelog-with-custom-no-release-signature.md
          no-release-signature: '/^_No functional changes made._$/m'

      - name: Print validation outputed release-type
        run: echo "${{ steps.validate.outputs.release-type }}"

  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test release with custom notice
        id: custom-notice-release
        uses: ./release
        with:
          path: ./src/fixtures/changelog.md
          notice: "Changeset: [#${{ github.event.number }}](https://github.com/${{ github.event.repository.name }}/pull/${{github.event.number}})."

      - name: Print release outputed version
        run: echo "${{ steps.custom-notice-release.outputs.version }}"

      - name: Print release outputed content
        run: echo "${{ steps.custom-notice-release.outputs.content }}"
      
      - name: Check custom notice in release output
        run: |
          EXPECTED="Changeset: [#${{ github.event.number }}](https://github.com/${{ github.repository }}/pull/${{ github.event.number }})."
          if [[ "${{ steps.custom-notice-release.outputs.content }}" == *"$EXPECTED"* ]]; then
            echo "Custom notice found in release output."
          else
            echo "Custom notice NOT found in release output."
            exit 1
          fi
